## Contributing

Thanks for stopping by and showing an interets in the project!

This is my first package, my first open project and the first time anyone is going to properly look at my code and try to use it. Yikees! So I could do with a lot of help, from really basic to very technical also.

### help with ideas

At this stage, the project can really benefit from basic ways in which the framework can be developed before the functions are finalised for the package. Here are a few initial idea forums

#### assess user needs [**ISSUE**](https://github.com/annakrystalli/rmacroRDM/issues/2)

as a first stage, I'm hoping to get some feedback on the features of the framework as they stand and what improvements or added features would better facilitate potential users workflows. So if you think the package might be useful to you, please don't hesitate to contribute suggestions towards improved functionality.

#### code review [**ISSUE**](https://github.com/annakrystalli/rmacroRDM/issues/3)

I'm sure my code could be improved by more experienced coders looking at this, so feel free to suggest and work on the code as a whole.  

#### data format [**ISSUE**](https://github.com/annakrystalli/rmacroRDM/issues/6)

Currently, the frameworks stores information in lists and dataframes. Could this be updated to better formats eg [`data.table`](https://cran.r-project.org/web/packages/data.table/vignettes/datatable-faq.pdf) or some sort of r database object?

#### standardising data specification [**ISSUE**](https://github.com/annakrystalli/rmacroRDM/issues/7)

Consensus on a basic level of data specification standards for the data products of the package would greatly enhance downstream usability and longevity of data. So, this could be a good space to begin discussing and synthesising what a model trait metadata structure would look like. How can we build both interoperability and flexibility in data management and specification?


<br>

***

### help develop

There are a number of features already proposed for development, detailed in the [roadmap](https://github.com/annakrystalli/rmacroRDM/blob/master/ROADMAP.Rmd) for this project.

### help in general

- open project management
- documentation

***

## Global Sprint

### Join me on **June 2-3** at the **[Mozilla Science Lab Global Sprint](https://mozillascience.org/global-sprint-2016)!**

I'll be available online to answer questions and discuss suggestions about all aspects of the project throughout the sprint. 
